from xhtml2pdf import pisa
from io import BytesIO
import logging

class PDFGenerator:
    @staticmethod
    def generate_report_pdf(html_content: str) -> BytesIO:
        """
        Convert HTML content to PDF.
        Returns a BytesIO object containing the PDF data.
        """
        # Create a BytesIO buffer to hold the PDF
        result_buffer = BytesIO()

        # Convert HTML to PDF
        pisa_status = pisa.CreatePDF(
            src=html_content,
            dest=result_buffer
        )

        # Check for errors
        if pisa_status.err:
            logging.error(f"PDF generation error: {pisa_status.err}")
            return None

        # Reset buffer position to the beginning
        result_buffer.seek(0)
        return result_buffer

    @staticmethod
    def get_styled_html(content_body: str, title: str = "Report") -> str:
        """
        Wrap content in a styled HTML template suitable for PDF generation.
        """
        return f"""
        <html>
        <head>
            <style>
                @page {{
                    size: A4;
                    margin: 2cm;
                    @frame footer_frame {{
                        -pdf-frame-content: footerContent;
                        bottom: 1cm;
                        margin-left: 2cm;
                        margin-right: 2cm;
                        height: 1cm;
                    }}
                }}
                
                body {{
                    font-family: Helvetica, Arial, sans-serif;
                    font-size: 12pt;
                    line-height: 1.5;
                    color: #333333;
                }}
                
                h1 {{
                    color: #2c3e50;
                    font-size: 24pt;
                    border-bottom: 2px solid #3498db;
                    padding-bottom: 10px;
                    margin-bottom: 20px;
                }}
                
                h2 {{
                    color: #2980b9;
                    font-size: 18pt;
                    margin-top: 30px;
                    margin-bottom: 15px;
                }}
                
                table {{
                    width: 100%;
                    border-collapse: collapse;
                    margin-bottom: 20px;
                }}
                
                th {{
                    background-color: #f2f2f2;
                    color: #333;
                    font-weight: bold;
                    padding: 10px;
                    text-align: left;
                    border-bottom: 2px solid #ddd;
                }}
                
                td {{
                    padding: 10px;
                    border-bottom: 1px solid #eee;
                }}
                
                .metric-container {{
                    display: block;
                    margin-bottom: 20px;
                    padding: 15px;
                    background-color: #f9f9f9;
                    border-radius: 5px;
                    border: 1px solid #e0e0e0;
                }}
                
                .metric-value {{
                    font-size: 20pt;
                    font-weight: bold;
                    color: #27ae60;
                }}
                
                .metric-label {{
                    font-size: 10pt;
                    color: #7f8c8d;
                    text-transform: uppercase;
                }}
                
                .footer {{
                    color: #7f8c8d;
                    font-size: 9pt;
                    text-align: center;
                }}
                
                .status-active {{ color: #27ae60; font-weight: bold; }}
                .status-inactive {{ color: #c0392b; font-weight: bold; }}
            </style>
        </head>
        <body>
            <h1>{title}</h1>
            {content_body}
            
            <div id="footerContent" class="footer">
                Generated by InboxQualify • Page <pdf:pagenumber> of <pdf:pagecount>
            </div>
        </body>
        </html>
        """
